### ISSUE TITLE
Releases Through GitHub/F-Droid Repo

### ISSUE THREAD

**Issue by Hamster45105** [TaeHagen/bluebubbles-app#15]
For those of us that don't like using Google Play, it would be great if the app could also be released through GitHub releases or a custom F-Droid repo.

**Comment by TaeHagen** [comment]
Google holds my private keys; I cannot do that at this point in time. Use Aurora store if you must.

**Comment by suprstarrd** [comment]
Sorry for the necropost, but figured I'd chime in with a few cents. Also would probably be good info for any other developer in this situation. (And to be clear: I support this issue and hope it can come to fruition in any way possible. I use GrapheneOS and I try to use Obtainium to obtain app binaries directly from their source before going to a third-party app store that isn't Accrescent or the built-in App Store app.)

@TaeHagen 
* Do you mean [Play App Signing](https://support.google.com/googleplay/android-developer/answer/9842756)? If so, I don't see why that would change anything for this to be possible. You can download a signed APK from the Play Console's [App bundle explorer](https://play.google.com/console/developers/app/bundle-explorer) to distribute elsewhere, including in an F-Droid repo or on GitHub Releases - although I understand that putting all of that work in would likely be a low priority. If you can upload a version with no proprietary libraries to Google Play (perhaps with [a test track](https://support.google.com/googleplay/android-developer/answer/9845334)?), then I see no reason the main F-Droid repository couldn't include it. You could, of course, also just sign it yourself anyway - it would just mean a user who obtained it from Google Play wouldn't be able to redownload it anywhere else. 
* If your apps end up in the main F-Droid repository ([at the moment there are roadblocks to that happening](https://f-droid.org/docs/Inclusion_Policy/)), the builds that the official F-Droid app downloads from there are [likely going to be signed by the F-Droid team](https://f-droid.org/docs/FAQ_-_App_Developers/#what-about-signing). [Apps with reproducible builds](https://f-droid.org/en/docs/Reproducible_Builds/) are exceptions to the rule, but regardless, that won't apply if you have your own repository that F-Droid users have to import themselves because your repository is outside of F-Droid's control.
* You may also consider [IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/info), one of the most popular third-party F-Droid repositories where all apps are signed by the developers. [I believe the app is much closer to passing their inclusion policy](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Inclusion%20Policy), but I think it does miss a mark or two.
* You may *also* consider [Accrescent](https://accrescent.app) - one of, if not *the* most secure and private Android app store I know of [for all of its features](https://accrescent.app/features). It is also mirrored in the [GrapheneOS](https://grapheneos.org) App Store. 
* Also, some developers choose to make the package identifiers for their apps unique for the store installation to work around app signing conflicts (e.g. one bundle ID ends in `.play` and another ends in `.fdroid`). Perhaps that would be useful here, too - and would certainly be required if you want to put the app in the main F-Droid repository due to a rule on package identifiers being associated with a domain you control. Until a developer associated with this project owns `openbubbles D0T com`, no dice...

**Comment by UlyssesZh** [comment]
The best course of action is to add a build flavor specific to F-Droid (with reproducible build) and GitHub release with a different package name and sign it with your own key.

**Comment by agamsingh9** [comment]
@TaeHagen Is this in the works? Not being in an F-droid repo is the only thing stopping me from installing this app.

**Comment by TaeHagen** [comment]
At this point, I don't think so. I don't want the hassle of deploying to multiple app stores. I would recommend installing the app through the aurora store.

**Comment by UlyssesZh** [comment]
You can have it automatically released using GitHub Actions. There will be no additional hassle after you set it up.

**Comment by agamsingh9** [comment]
@TaeHagen At least write up a quick guide on building from source as there is no way of confirming that the app on the Play Store is built from this repo. Open source doesn't really mean anything without a reproducible build process.

That would help ease a lot of [privacy/security issues](https://reports.exodus-privacy.eu.org/en/reports/655137/) with your software.
